# Specify a base image
FROM node:alpine
WORKDIR /client
COPY ./package.json ./
RUN npm install && npm install -g serve
COPY ./ ./
RUN npm run build
EXPOSE 3002

# Default Command
CMD ["serve", "-p", "3002", "-s", "build"]
