# Specify a base image
FROM node:alpine
WORKDIR /client

# Install some dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm install -g serve
RUN npm run build
EXPOSE 3002

# Default Command
CMD ["serve", "-p", "3002", "-s", "build"]