# Specify a base image
FROM node:alpine As builder
WORKDIR /client
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run build

# Install some dependencies
FROM node:alpine
RUN npm install -g serve
WORKDIR /client
COPY --from=builder /client/build .
EXPOSE 3002

# Default Command
CMD ["serve", "-p", "3002", "-s", "build"]
