version: '3.7'
services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: .env
    environment: 
      - BACKEND_PORT=$BACKEND_PORT
      - BACKEND_SERVER_TEST=$BACKEND_SERVER_TEST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - BACKEND_SECRET=$BACKEND_SECRET
    ports:
      - "3001:3001"
    depends_on:
      - mongo_db
    networks:
      - shopthing
      
  client:
    container_name: client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    env_file: .env
    environment: 
      - NODE_PATH=$NODE_PATH
      - REACT_APP_BACKEND_SERVER=$REACT_APP_BACKEND_SERVER  
    ports:
        - "3002:3002"
    networks:
      - shopthing
          
  nginx:
    container_name: ngnix
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
    networks:
      - shopthing

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    env_file: .env
    environment: 
      - MONGO_PORT=$MONGO_PORT
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    volumes:
      #: ro, readonly
      - ./mongodb/db_setup.sh:/docker-entrypoint-initdb.d/db_setup.sh:ro
      - ./mongodb/mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - shopthing
  
volumes:
  mongo_data:
    
networks:
  shopthing: